<?php

namespace Drupal\generator\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Configuration custom settings for form.
 */
class GeneratorSettingsForm extends ConfigFormBase {

  /**
   * Config settings.
   *
   * @var string
   */
  const SETTINGS = 'generator.settings';

  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames()
  {
    return [
      self::SETTINGS,
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId()
  {
    return 'generator_settings_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $config = $this->config(static::SETTINGS);

    $form['content_type'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Content type'),
      '#description' => $this->t('Choose content type for generating nodes.'),
      '#default_value' => $config->get('content_type'),
    ];

    $form['quantity'] = [
      '#type' => 'number',
      '#title' => $this->t('Quantity'),
      '#description' => $this->t('Number of created nodes.'),
      '#default_value' => $config->get('quantity'),
      '#min' => 1,
      '#max' => 15,
    ];

    $form['random_images'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('Use random images'),
      '#description' => $this->t('If checked, module will use random images from media libriary.'),
      '#default_value' => $config->get('random_images'),
    ];

    return parent::buildForm($form, $form_state);
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {

    $this->configFactory->getEditable(static::SETTINGS)
      ->set('content_type', $form_state->getValue('content_type'))
      ->set('quantity', $form_state->getValue('quantity'))
      ->set('random_images', $form_state->getValue('random_images'))
      ->save();

    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
